### ISSUE TITLE
Project documentation generation

### ISSUE THREAD

**Issue by bongo227** [tpb1908/AndroidProjectsClient#232]
I was looking for a way to include code in the project documentation without the need to update it so I created a small [script](https://gist.github.com/bongo227/fdd8e8bb608921c0c7ccd8c2f11b6075) that allows you to import files into markdown using `#import "path/to/file"`. I added a pre-commit hook to generate the markdown file and a link to [gitprint](gitprint.com) to create a pdf. 

Just thought it might be usefull to you considering the amount of code you will have!

**Comment by tpb1908** [comment]
Thanks. I might add imports for methods.

What are you using for markdown editing?

**Comment by bongo227** [comment]
Just vscode.

Are you planning to document each method separately then?

**Comment by tpb1908** [comment]
No, but some classes (e.g. networking or utilities) don't make much sense to document all at once as they are used project wide and aren't dependent on anything else.

**Comment by bongo227** [comment]
That makes sense, shouldn't be to hard to do.

**Comment by tpb1908** [comment]
I added filetypes for highlighting.
https://gist.github.com/tpb1908/2e5b2eb2be50cdc95ed258d1dcad2b00
